/// @description Initializes variables
// You can write your code in this editor
object_level1_monster_smallZombie_stat_attack=5;
object_level1_monster_smallZombie_stat_HP=5;
object_level1_monster_smallZombie_stat_speed=25/60;
object_level1_monster_smallZombie_stat_knockbackResistance=1;
object_level1_monster_smallZombie_stat_alive=true;
object_level1_monster_smallZombie_logic_damaged=false;
direction=point_direction(x,y,obj_altar.x,obj_altar.y);
speed=object_level1_monster_smallZombie_stat_speed;